# Copyright © 2026 Jonson Wang
# Auto-generated by tools/gen_symbol_packs.py — DO NOT edit by hand.
# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。

class_name GPSymbolPackIso_10628
extends RefCounted


# Auto-generated symbol definitions for iso_10628.
# 图元包 %s 的自动生成图元定义。
# Source: ISO 10628 P&ID Symbols (sample)
# License: MIT
# Upstream author: sample
# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。


static func gpDefs() -> Array[GPSymbolDef]:
	var gpOut: Array[GPSymbolDef] = []
	gpOut.append(_gpMk("BV_BallValve_001", "球阀", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[75.833, 50], [100, 50]], "closed": false}, {"pts": [[41.667, 37.5], [63.333, 62.5]], "closed": false}], "circles": [{"c": [52.5, 50], "r": 14.167}], "rects": [], "box": [-10, 33, 120, 34]}, Vector2(64, 48)))
	gpOut.append(_gpMk("CHK_CheckValve_001", "止回阀", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[29.167, 33.333], [62.5, 50], [29.167, 66.667], [29.167, 33.333]], "closed": true}, {"pts": [[62.5, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 49.5, 120, 1]}, Vector2(64, 48)))
	gpOut.append(_gpMk("CV_ControlValve_001", "调节阀", "valve", [], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[25, 33.333], [66.667, 50], [25, 66.667], [25, 33.333]], "closed": true}, {"pts": [[66.667, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 49.5, 120, 1]}, Vector2(64, 48)))
	gpOut.append(_gpMk("C_Compressor_001", "压缩机", "pump", [], {"paths": [{"pts": [[16.667, 50], [41.667, 33.333], [75, 33.333], [91.667, 50], [75, 66.667], [41.667, 66.667], [16.667, 50]], "closed": true}, {"pts": [[0, 50], [16.667, 50]], "closed": false}, {"pts": [[91.667, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 49.5, 120, 1]}, Vector2(80, 56)))
	gpOut.append(_gpMk("DV_DiaphragmValve_001", "隔膜阀", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[29.167, 41.667], [32.35, 43.056], [34.954, 44.444], [36.979, 45.833], [38.426, 47.222], [39.294, 48.611], [39.583, 50], [39.294, 51.389], [38.426, 52.778], [36.979, 54.167], [34.954, 55.556], [32.35, 56.944], [29.167, 58.333]], "closed": false}, {"pts": [[70.833, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 40, 120, 20]}, Vector2(64, 48)))
	gpOut.append(_gpMk("ElectricalLine_DotDash_001", "Electricalline Dotdash 001", "general", [], {"paths": [{"pts": [[0, 49.737], [100, 49.737]], "closed": false}], "circles": [], "rects": [], "box": [-45, 49.5, 190, 1]}, Vector2(64, 64)))
	gpOut.append(_gpMk("FE_FieldEnclosure_001", "现场接线箱", "instrument", [], {"paths": [{"pts": [[0, 37.5], [100, 37.5]], "closed": false}], "circles": [], "rects": [{"pos": [0, 12.5], "size": [100, 75]}], "box": [10, 20, 80, 60]}, Vector2(56, 56)))
	gpOut.append(_gpMk("FI_FlowIndicator_001", "流量指示器", "instrument", [], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 35}], "rects": [], "box": [10, 22, 80, 56]}, Vector2(56, 56)))
	gpOut.append(_gpMk("FT_FlowTransmitter_001", "流量变送器", "instrument", [], {"paths": [{"pts": [[50, 59.574], [50, 80.851]], "closed": false}], "circles": [{"c": [50, 29.787], "r": 29.787}], "rects": [{"pos": [13.83, 80.851], "size": [72.34, 19.149]}], "box": [16, 3, 68, 94]}, Vector2(56, 56)))
	gpOut.append(_gpMk("GLV_GlobeValve_001", "截止阀", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[29.167, 38.333], [32.35, 40.278], [34.954, 42.222], [36.979, 44.167], [38.426, 46.111], [39.294, 48.056], [39.583, 50], [39.294, 51.944], [38.426, 53.889], [36.979, 55.833], [34.954, 57.778], [32.35, 59.722], [29.167, 61.667]], "closed": false}, {"pts": [[70.833, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 36, 120, 28]}, Vector2(64, 48)))
	gpOut.append(_gpMk("GV_GateValve_001", "闸阀", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[70.833, 50], [100, 50]], "closed": false}], "circles": [], "rects": [{"pos": [29.167, 38.333], "size": [41.667, 23.333]}], "box": [-10, 36, 120, 28]}, Vector2(64, 48)))
	gpOut.append(_gpMk("HX_HeatExchanger_001", "换热器", "heat", [], {"paths": [{"pts": [[47.143, 32.857], [52.857, 32.857]], "closed": false}, {"pts": [[47.143, 67.143], [52.857, 67.143]], "closed": false}, {"pts": [[0, 50], [7.143, 50]], "closed": false}, {"pts": [[92.857, 50], [100, 50]], "closed": false}], "circles": [], "rects": [{"pos": [7.143, 32.857], "size": [40, 34.286]}, {"pos": [52.857, 32.857], "size": [40, 34.286]}], "box": [-20, 26, 140, 48]}, Vector2(84, 64)))
	gpOut.append(_gpMk("InstrumentLine_Dashed_001", "Instrumentline Dashed 001", "general", [], {"paths": [{"pts": [[0, 49.737], [100, 49.737]], "closed": false}], "circles": [], "rects": [], "box": [-45, 49.5, 190, 1]}, Vector2(64, 64)))
	gpOut.append(_gpMk("LI_LevelIndicator_001", "液位指示器", "instrument", [], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 35}], "rects": [], "box": [10, 22, 80, 56]}, Vector2(56, 56)))
	gpOut.append(_gpMk("LT_LevelTransmitter_001", "液位变送器", "instrument", [], {"paths": [{"pts": [[50, 59.574], [50, 80.851]], "closed": false}], "circles": [{"c": [50, 29.787], "r": 29.787}], "rects": [{"pos": [13.83, 80.851], "size": [72.34, 19.149]}], "box": [16, 3, 68, 94]}, Vector2(56, 56)))
	gpOut.append(_gpMk("PD_PositiveDisplacementPump_001", "容积泵", "pump", [], {"paths": [{"pts": [[75, 50], [74.52, 52.926], [73.097, 55.74], [70.787, 58.334], [67.678, 60.607], [63.889, 62.472], [59.567, 63.858], [54.877, 64.712], [50, 65], [45.123, 64.712], [40.433, 63.858], [36.111, 62.472], [32.322, 60.607], [29.213, 58.334], [26.903, 55.74], [25.48, 52.926], [25, 50], [25.48, 47.074], [26.903, 44.26], [29.213, 41.666], [32.322, 39.393], [36.111, 37.528], [40.433, 36.142], [45.123, 35.288], [50, 35], [54.877, 35.288], [59.567, 36.142], [63.889, 37.528], [67.678, 39.393], [70.787, 41.666], [73.097, 44.26], [74.52, 47.074]], "closed": true}, {"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [], "rects": [], "box": [-10, 49.5, 120, 1]}, Vector2(80, 56)))
	gpOut.append(_gpMk("PI_PressureIndicator_001", "压力指示器", "instrument", [], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 35}], "rects": [], "box": [10, 22, 80, 56]}, Vector2(56, 56)))
	gpOut.append(_gpMk("PT_PressureTransmitter_001", "压力变送器", "instrument", [], {"paths": [{"pts": [[50, 59.574], [50, 80.851]], "closed": false}], "circles": [{"c": [50, 29.787], "r": 29.787}], "rects": [{"pos": [13.83, 80.851], "size": [72.34, 19.149]}], "box": [16, 3, 68, 94]}, Vector2(56, 56)))
	gpOut.append(_gpMk("PV_Positioner_001", "阀门定位器", "valve", [], {"paths": [{"pts": [[0, 50], [29.167, 50]], "closed": false}, {"pts": [[70.833, 50], [100, 50]], "closed": false}], "circles": [], "rects": [{"pos": [29.167, 37.5], "size": [41.667, 25]}], "box": [-10, 35, 120, 30]}, Vector2(64, 48)))
	gpOut.append(_gpMk("P_CentrifugalPump_001", "离心泵", "pump", [], {"paths": [{"pts": [[0, 50], [16.667, 50]], "closed": false}, {"pts": [[83.333, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 11.667}], "rects": [{"pos": [16.667, 33.333], "size": [66.667, 33.333]}], "box": [-10, 30, 120, 40]}, Vector2(80, 56)))
	gpOut.append(_gpMk("ProcessLine_Solid_001", "Processline Solid 001", "general", [], {"paths": [{"pts": [[0, 49.737], [100, 49.737]], "closed": false}], "circles": [], "rects": [], "box": [-45, 49.5, 190, 1]}, Vector2(64, 64)))
	gpOut.append(_gpMk("TI_TemperatureIndicator_001", "温度指示器", "instrument", [], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 35}], "rects": [], "box": [10, 22, 80, 56]}, Vector2(56, 56)))
	gpOut.append(_gpMk("TK_Tank_001", "储罐", "tank", [], {"paths": [{"pts": [[0, 50], [100, 50]], "closed": false}], "circles": [], "rects": [{"pos": [0, 0], "size": [100, 100]}], "box": [10, 10, 80, 80]}, Vector2(72, 96)))
	gpOut.append(_gpMk("TT_TemperatureTransmitter_001", "温度变送器", "instrument", [], {"paths": [{"pts": [[50, 59.574], [50, 80.851]], "closed": false}], "circles": [{"c": [50, 29.787], "r": 29.787}], "rects": [{"pos": [13.83, 80.851], "size": [72.34, 19.149]}], "box": [16, 3, 68, 94]}, Vector2(56, 56)))
	gpOut.append(_gpMk("VAV_ValveActuator_001", "阀门执行器", "valve", [], {"paths": [{"pts": [[0, 50], [32.143, 50]], "closed": false}, {"pts": [[67.857, 50], [100, 50]], "closed": false}], "circles": [{"c": [50, 50], "r": 4.286}], "rects": [{"pos": [32.143, 39.286], "size": [35.714, 21.429]}], "box": [-20, 35, 140, 30]}, Vector2(64, 48)))
	return gpOut


# Internal helper: build one SymbolDef from parsed data.
# 内部辅助：从解析数据构造一个 SymbolDef。
static func _gpMk(gpId: String, gpChineseName: String, gpCat: String, gpPorts: Array[Dictionary], gpShape: Dictionary, gpEnv: Vector2) -> GPSymbolDef:
	var gpD: GPSymbolDef = GPSymbolDef.new()
	gpD.gpId = gpId
	gpD.gpDisplayName = gpChineseName
	gpD.gpCategory = gpCat
	gpD.gpDefaultSize = gpEnv
	gpD.gpPorts = gpPorts
	gpD.gpShape = gpShape
	return gpD
