# Copyright © 2026 Jonson Wang
# MIT License — generated from assets/symbol_packs/open-pid-icons/open-pid-icons.json
# (upstream: open-pid-icons npm, MIT, Copyright 2025 tbo47)
# Auto-generated by tools/gen_openpid_defs.py — DO NOT edit by hand.
# 自动生成，请勿手改；修改请编辑 tools/gen_openpid_defs.py 后重跑。

extends RefCounted

const GPSymbolDef := preload("res://src/core/symbol_def.gd")


# Build the open-pid-icons vector symbol definitions (shape normalized 0..100 per axis).
# 构造 open-pid-icons 矢量图元定义（形状按轴归一化到 0..100）。
static func gpDefs() -> Array[GPSymbolDef]:
	var gpOut: Array[GPSymbolDef] = []
	gpOut.append(_gpMk("hand_operated_gate_valve", "手动闸阀", "valve", Vector2(71, 46), [{"name": "p1", "pos": [-37.53, 7.67]}, {"name": "p2", "pos": [35.50, 7.67]}], {"paths": [{"pts": [[0, 33.33], [0, 100], [100, 33.33], [100, 100], [0, 33.33]], "closed": true}, {"pts": [[50, 66.67], [50, 0]], "closed": false}, {"pts": [[28.57, 0], [71.43, 0]], "closed": false}], "circles": [], "rects": []}))
	gpOut.append(_gpMk("gate_valve", "闸阀", "valve", Vector2(71, 31), [{"name": "p1", "pos": [-35.50, 0]}, {"name": "p2", "pos": [35.50, 0]}], {"paths": [{"pts": [[0, 0], [0, 100], [100, 0], [100, 100], [0, 0]], "closed": false}], "circles": [], "rects": []}))
	gpOut.append(_gpMk("hand_operated_globe_valve", "手动截止阀", "valve", Vector2(71, 46), [{"name": "p1", "pos": [-35.50, 7.67]}, {"name": "p2", "pos": [35.50, 7.67]}], {"paths": [{"pts": [[0, 33.33], [0, 100], [100, 33.33], [100, 100], [0, 33.33]], "closed": true}, {"pts": [[50, 66.67], [50, 0]], "closed": false}, {"pts": [[28.57, 0], [71.43, 0]], "closed": false}, {"pts": [[40, 66.67], [40, 66.67], [40.15, 63.97], [40.60, 61.35], [41.34, 58.89], [42.34, 56.67], [43.57, 54.75], [45, 53.20], [46.58, 52.05], [48.26, 51.35], [50, 51.11], [51.74, 51.35], [53.42, 52.05], [55, 53.20], [56.43, 54.75], [57.66, 56.67], [58.66, 58.89], [59.40, 61.35], [59.85, 63.97], [60, 66.67], [60, 66.67], [59.85, 69.37], [59.40, 71.99], [58.66, 74.44], [57.66, 76.67], [56.43, 78.58], [55, 80.14], [53.42, 81.28], [51.74, 81.99], [50, 82.22], [48.26, 81.99], [46.58, 81.28], [45, 80.14], [43.57, 78.58], [42.34, 76.67], [41.34, 74.44], [40.60, 71.99], [40.15, 69.37], [40, 66.67]], "closed": false}], "circles": [], "rects": []}))
	gpOut.append(_gpMk("rotary_valve", "旋转阀", "valve", Vector2(141, 71), [{"name": "p1", "pos": [-70.50, 0]}, {"name": "p2", "pos": [68.49, 0]}], {"paths": [{"pts": [[0, 50], [25, 50]], "closed": false}, {"pts": [[25, 0], [25, 100]], "closed": false}, {"pts": [[25, 50], [25, 50], [25.38, 41.32], [26.51, 32.90], [28.35, 25], [30.85, 17.86], [33.93, 11.70], [37.50, 6.70], [41.45, 3.02], [45.66, 0.76], [50, 0], [54.34, 0.76], [58.55, 3.02], [62.50, 6.70], [66.07, 11.70], [69.15, 17.86], [71.65, 25], [73.49, 32.90], [74.62, 41.32], [75, 50], [75, 50], [74.62, 58.68], [73.49, 67.10], [71.65, 75], [69.15, 82.14], [66.07, 88.30], [62.50, 93.30], [58.55, 96.98], [54.34, 99.24], [50, 100], [45.66, 99.24], [41.45, 96.98], [37.50, 93.30], [33.93, 88.30], [30.85, 82.14], [28.35, 75], [26.51, 67.10], [25.38, 58.68], [25, 50]], "closed": false}, {"pts": [[75, 0], [75, 100]], "closed": false}, {"pts": [[75, 50], [100, 50]], "closed": false}], "circles": [], "rects": []}))
	gpOut.append(_gpMk("check_valve", "止回阀", "valve", Vector2(161, 31), [{"name": "p1", "pos": [-80.50, -1.03]}, {"name": "p2", "pos": [78.49, -1.03]}], {"paths": [{"pts": [[0, 50], [28.12, 50]], "closed": false}, {"pts": [[28.12, 100], [28.12, 0], [71.88, 100], [66.88, 96.67]], "closed": false}, {"pts": [[71.88, 100], [68.12, 80]], "closed": false}, {"pts": [[71.88, 100], [71.88, 0]], "closed": false}, {"pts": [[71.88, 50], [100, 50]], "closed": false}], "circles": [], "rects": []}))
	gpOut.append(_gpMk("tank", "储罐", "tank", Vector2(141, 233), [{"name": "p1", "pos": [-70.50, -97.38]}, {"name": "p2", "pos": [-70.50, 83.33]}, {"name": "p3", "pos": [70.50, -97.38]}, {"name": "p4", "pos": [70.50, 83.33]}], {"paths": [{"pts": [[0, 4.76], [0, 95.24], [0, 95.24], [5.47, 96.24], [10.97, 97.12], [16.49, 97.88], [22.04, 98.53], [27.61, 99.06], [33.20, 99.47], [38.79, 99.76], [44.39, 99.94], [50, 100], [55.61, 99.94], [61.21, 99.76], [66.80, 99.47], [72.39, 99.06], [77.96, 98.53], [83.51, 97.88], [89.03, 97.12], [94.53, 96.24], [100, 95.24], [100, 4.76], [100, 4.76], [94.53, 3.76], [89.03, 2.88], [83.51, 2.12], [77.96, 1.47], [72.39, 0.94], [66.80, 0.53], [61.21, 0.24], [55.61, 0.06], [50, 0], [44.39, 0.06], [38.79, 0.24], [33.20, 0.53], [27.61, 0.94], [22.04, 1.47], [16.49, 2.12], [10.97, 2.88], [5.47, 3.76], [0, 4.76]], "closed": false}], "circles": [], "rects": []}))
	return gpOut


# Internal: build one open-pid-icon SymbolDef from parsed data.
# 内部：从解析数据构造一个 open-pid-icons 图元定义。
static func _gpMk(gpId: String, gpName: String, gpCat: String, gpSize: Vector2, gpPorts: Array[Dictionary], gpShape: Dictionary) -> GPSymbolDef:
	var gpD: GPSymbolDef = GPSymbolDef.new()
	gpD.gpId = gpId
	gpD.gpDisplayName = gpName
	gpD.gpCategory = gpCat
	gpD.gpDefaultSize = gpSize
	gpD.gpPorts = gpPorts
	gpD.gpShape = gpShape
	gpD.gpIconPath = "res://assets/symbol_packs/open-pid-icons/svg/%s.svg" % gpId
	return gpD
