#!/usr/bin/env python3
# tools/gen_symbol_packs.py
# Unified symbol pack generator.
# 统一图元包生成器。
#
# Reads every subfolder of assets/symbol_packs/ that contains a manifest.json,
# strips text from each SVG, normalizes shape primitives into the 100x100 unit
# box, emits a GDScript defs file under src/core/symbol_packs/.
# 读取 assets/symbol_packs/ 下每个含 manifest.json 的子包，
# 剔除 SVG 中的 text 元素，把形状原语归一化到 100x100 单位框，
# 并在 src/core/symbol_packs/ 下生成对应的 GDScript 定义文件。
#
# Usage / 用法:
#   python3 tools/gen_symbol_packs.py
#
# Output / 输出:
#   src/core/symbol_packs/pack_<pack_id>.gd   (one per discovered pack)
#                                              （每个已发现的图元包输出一个文件）

import json
import os
import re
import sys
import xml.etree.ElementTree as ET

# Reuse the path parser from the sibling converter.
# 复用同目录转换器的路径解析器。
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import svg_to_gpsym as S  # noqa: E402
from svg_to_gpsym import _apply, _mul, _parse_transform  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Godot-PID-Core
PACKS_DIR = os.path.join(ROOT, "assets", "symbol_packs")
OUT_DIR = os.path.join(ROOT, "src", "core", "symbol", "symbol_packs")

# License header for every emitted GDScript file.
# 每个输出 GDScript 文件的许可证头。
HEADER = """\
# Copyright © 2026 Jonson Wang
# Auto-generated by tools/gen_symbol_packs.py — DO NOT edit by hand.
# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。
"""


def _read_nominal():
    # Parse GP_NOMINAL from src/core/symbol_categories.gd so sizes stay in sync.
    # 从 src/core/symbol_categories.gd 解析 GP_NOMINAL，使尺寸与枚举表保持一致。
    cat_path = os.path.join(ROOT, "src", "core", "symbol", "symbol_categories.gd")
    with open(cat_path, "r", encoding="utf-8") as f:
        text = f.read()
    block = re.search(r"const\s+GP_NOMINAL[^{]*\{(.*?)\}", text, re.S)
    sizes = {}
    if block:
        for k, w, h in re.findall(
            r'"([^"]+)"\s*:\s*Vector2\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)', block.group(1)
        ):
            sizes[k] = (float(w), float(h))
    return sizes


def _strip_text_elements(svg_path):
    # Parse SVG, remove all <text> elements, return new XML root.
    # 解析 SVG，删除所有 <text> 元素，返回新根节点。
    tree = ET.parse(svg_path)
    ns = "http://www.w3.org/2000/svg"
    for t in list(tree.getroot().iter(ns + "text")):
        t.getparent().remove(t)
    return tree.getroot()


def _shape_with_box(root, size=100):
    # Use svg_to_gpsym._collect for full SVG element support, then compute unit-box.
    # 用 svg_to_gpsym._collect 处理完整 SVG 元素，再计算单位空间包围盒。
    # Returns (paths, circles, rects, minx, maxx, miny, maxy) in the ORIGINAL SVG coords.
    # 返回原始 SVG 坐标系下的 (折线列表, 圆列表, 矩形列表, 包围盒).
    result = S._collect(root, size, "general")
    if result is None:
        return None
    # _collect already normalizes into 100x100; we need the ORIGINAL bounding box
    # to compute the "box" field. Walk the original root for raw pts.
    ns = "http://www.w3.org/2000/svg"
    raw_pts = []
    def walk(el, m):
        if "transform" in el.attrib:
            m = S._mul(m, S._parse_transform(el.attrib["transform"]))
        tag = S._localname(el.tag)
        if tag in ("path", "rect", "circle", "line", "polygon", "polyline"):
            if tag == "line":
                x1 = float(el.attrib.get("x1", 0)); y1 = float(el.attrib.get("y1", 0))
                x2 = float(el.attrib.get("x2", 0)); y2 = float(el.attrib.get("y2", 0))
                raw_pts.append(S._apply(m, x1, y1)); raw_pts.append(S._apply(m, x2, y2))
            elif tag == "rect":
                x = float(el.attrib.get("x", 0)); y = float(el.attrib.get("y", 0))
                w = float(el.attrib.get("width", 0)); h = float(el.attrib.get("height", 0))
                for px, py in [(x, y), (x+w, y), (x, y+h), (x+w, y+h)]:
                    raw_pts.append(S._apply(m, px, py))
            elif tag == "circle":
                cx = float(el.attrib.get("cx", 0)); cy = float(el.attrib.get("cy", 0))
                r = float(el.attrib.get("r", 0))
                raw_pts.append(S._apply(m, cx-r, cy-r)); raw_pts.append(S._apply(m, cx+r, cy+r))
            elif tag == "path":
                d = el.attrib.get("d", "")
                for poly, _ in S._path_to_polylines(d):
                    for p in poly:
                        raw_pts.append(S._apply(m, p[0], p[1]))
        for child in el:
            walk(child, m)
    walk(root, S._ident())
    if not raw_pts:
        return None
    xs = [p[0] for p in raw_pts]; ys = [p[1] for p in raw_pts]
    minx, maxx = min(xs), max(xs); miny, maxy = min(ys), max(ys)
    return result["paths"], result["circles"], result["rects"], minx, maxx, miny, maxy


def _build_shape(paths, circles, rects, minx, maxx, miny, maxy):
    # Build gpShape dict with box field (unit-space bbox).
    # 构建 gpShape 字典，含单位空间包围盒 box。
    uw = (maxx - minx) or 1.0
    uh = (maxy - miny) or 1.0
    box = [round(50.0 - uw * 0.5, 2), round(50.0 - uh * 0.5, 2), round(uw, 2), round(uh, 2)]
    return {"paths": paths, "circles": circles, "rects": rects, "box": box}


def _infer_category(svg_path, csv_path):
    # Infer category from SVG filename using mapping.csv (ISO) or icon "type" field (IEC).
    # 通过 mapping.csv（ISO）或图标 "type" 字段（IEC）从文件名推断类别。
    base = os.path.splitext(os.path.basename(svg_path))[0]
    cat = "general"
    if csv_path and os.path.exists(csv_path):
        with open(csv_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith(base + ",") or f'"{base}.svg"' in line:
                    parts = line.strip().split(",")
                    if len(parts) >= 2:
                        isa_code = parts[1].strip()
                        # Map ISA code to category.
                        # 把 ISA 代码映射到类别。
                        cat_map = {
                            "P": "pump", "PD": "pump", "C": "pump",
                            "GV": "valve", "GLV": "valve", "BV": "valve",
                            "CHK": "valve", "DV": "valve", "CV": "valve",
                            "VAV": "valve", "PV": "valve",
                            "TK": "tank",
                            "HX": "heat",
                            "FT": "instrument", "PT": "instrument", "TT": "instrument",
                            "LT": "instrument", "FI": "instrument", "PI": "instrument",
                            "TI": "instrument", "LI": "instrument", "FE": "instrument",
                            "LINE-P": "pipe", "LINE-I": "pipe", "LINE-E": "pipe",
                        }
                        cat = cat_map.get(isa_code, "general")
                        break
    return cat


# ---- Port tables (P1) ----
# ---- 端口表（P1）----
# Why a literal table instead of scraping the SVG: the previous _infer_ports_svg was dead code.
# It scanned for namespace-prefixed tags ("{http://www.w3.org/2000/svg}line") while the ISO SVGs
# carry bare tags, so it always returned [] — which is why every built-in symbol shipped with
# no ports. It also computed a bounding box and then returned hard-coded constants anyway.
# An explicit table is reviewable, matches GP_STD_PORTS / GP_PORT_OVERRIDES in
# src/core/symbol/symbol_categories.gd, and is what gp_test_symbol_pack.gd asserts against.
# 为何用字面表而非扫描 SVG：先前的 _infer_ports_svg 是死代码。它按带命名空间前缀的标签
# ("{http://www.w3.org/2000/svg}line") 扫描，而 ISO 的 SVG 是裸标签，故恒返回 [] —— 这正是
# 每个内置图元都没有端口的原因。它还算出包围盒后仍返回硬编码常量。字面表可审阅、与
# src/core/symbol/symbol_categories.gd 的 GP_STD_PORTS / GP_PORT_OVERRIDES 一致，
# 且由 gp_test_symbol_pack.gd 断言。
#
# "type" is the port purpose / "type" 为端口用途：
#   NOZZLE 工艺管口（接管道）/ ACTUATOR 阀门执行机构（接信号线）
#   SIGNAL 仪表信号端子（接信号线）/ TERMINAL 通用端点
STD_PORTS = {
    "valve": [
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
    ],
    "pump": [
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
    ],
    "heat": [
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
    ],
    "tank": [
        {"name": "top", "pos": [0.5, 0.0], "dir": [0, -1], "type": "NOZZLE"},
        {"name": "bottom", "pos": [0.5, 1.0], "dir": [0, 1], "type": "NOZZLE"},
    ],
    # A transmitter taps the process (proc, bottom) and emits a signal (sig, top).
    # 变送器从工艺侧取压/取样（proc 在下），并向上发出信号（sig 在上）。
    "instrument": [
        {"name": "proc", "pos": [0.5, 1.0], "dir": [0, 1], "type": "NOZZLE"},
        {"name": "sig", "pos": [0.5, 0.0], "dir": [0, -1], "type": "SIGNAL"},
    ],
    "general": [],
}

# Per-symbol overrides, keyed by symbol id. A present key REPLACES the category table entirely,
# so a four-nozzle heat exchanger does not have to inherit a two-nozzle default.
# 按符号 id 的端口覆盖表。存在该键即「整体替换」类别表，故四管口换热器无需继承两管口默认值。
PORT_OVERRIDES = {
    # 换热器：壳程两个 + 管程两个 / shell side x2 + tube side x2
    "LHEAT001": [  # 换热器
        {"name": "shell_in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "shell_out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
        {"name": "tube_in", "pos": [0.5, 0.0], "dir": [0, -1], "type": "NOZZLE"},
        {"name": "tube_out", "pos": [0.5, 1.0], "dir": [0, 1], "type": "NOZZLE"},
    ],
    # 储罐：顶 / 底 / 两侧 / tank: top, bottom and two side nozzles
    "LTANK001": [  # 储罐
        {"name": "top", "pos": [0.5, 0.0], "dir": [0, -1], "type": "NOZZLE"},
        {"name": "bottom", "pos": [0.5, 1.0], "dir": [0, 1], "type": "NOZZLE"},
        {"name": "left", "pos": [0.0, 0.25], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "right", "pos": [1.0, 0.75], "dir": [1, 0], "type": "NOZZLE"},
    ],
    # 调节阀 / 执行器 / 定位器：两个管口 + 顶部执行机构接点 / two nozzles + actuator terminal
    "LVALVE003": [  # 调节阀
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
        {"name": "act", "pos": [0.5, 0.0], "dir": [0, -1], "type": "ACTUATOR"},
    ],
    "LVALVE008": [  # 阀门执行器
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
        {"name": "act", "pos": [0.5, 0.0], "dir": [0, -1], "type": "ACTUATOR"},
    ],
    "LVALVE007": [  # 阀门定位器
        {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
        {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
        {"name": "act", "pos": [0.5, 0.0], "dir": [0, -1], "type": "ACTUATOR"},
    ],
    # 现场接线箱：两个信号端子，无工艺管口 / field enclosure: two signal terminals only
    "LINSTRUMENT001": [  # 现场接线箱
        {"name": "sig_in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "SIGNAL"},
        {"name": "sig_out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "SIGNAL"},
    ],
    # 线型图例符号：图例美术，故意不可连接 / legend glyphs, deliberately not connectable
    "LGENERAL003": [],  # 工艺实线 / process solid line
    "LGENERAL002": [],  # 仪表虚线 / instrument dashed line
    "LGENERAL001": [],  # 电气点划线 / electrical dot-dash line
}

# In-line indicators (FI/PI/TI/LI): the glyph is pierced left-to-right by the pipe, so they get
# two nozzles plus a signal terminal. Overrides for these ids are None -> this table is used.
# 就地指示表（FI/PI/TI/LI）：字形被管线左右贯穿，故两个管口 + 一个信号端子。
# 这些 id 的覆盖值为 None，即使用本表。
INLINE_INSTRUMENT = [
    {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0], "type": "NOZZLE"},
    {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0], "type": "NOZZLE"},
    {"name": "sig", "pos": [0.5, 0.0], "dir": [0, -1], "type": "SIGNAL"},
]
for _id in ("LINSTRUMENT002", "LINSTRUMENT006",
            "LINSTRUMENT008", "LINSTRUMENT004"):
    PORT_OVERRIDES[_id] = None


def _ports_for(symbol_id, cat):
    # Resolve a symbol's ports: explicit override wins, then the category table.
    # 解析某符号的端口：显式覆盖优先，其次类别表。
    if symbol_id in PORT_OVERRIDES:
        ov = PORT_OVERRIDES[symbol_id]
        return [dict(p) for p in (INLINE_INSTRUMENT if ov is None else ov)]
    return [dict(p) for p in STD_PORTS.get(cat, [])]


# Factory tag prefix per category (M9). Mirrors GPTagRule.GP_DEFAULT_CATEGORY_PREFIXES in
# core/model/tag_rule.gd — change BOTH or symbols will be numbered with a prefix the runtime
# does not recognise. / 各类别的出厂位号前缀（M9）。与 core/model/tag_rule.gd 中的
# GPTagRule.GP_DEFAULT_CATEGORY_PREFIXES 互为镜像 —— 两处须同步改，否则位号会带上运行期
# 不认识的前缀。
TAG_PREFIX = {
    "pump": "P",
    "valve": "V",
    "heat": "E",
    "tank": "T",
    "instrument": "I",
    "filter": "F",
    "general": "G",
}


def _tag_prefix(cat):
    # A symbol may opt out of the category convention; unknown categories simply carry no
    # prefix and let the runtime fall back to the category's first letter.
    # 图元可跳出类别约定；未知类别不带前缀，由运行期回落到类别首字母。
    return TAG_PREFIX.get(str(cat), "")


def _category_code(cat):
    # Letters only, upper-cased — mirrors GPSymbolNaming.gpCategoryCode.
    # 仅保留字母并大写 —— 与 GPSymbolNaming.gpCategoryCode 一致。
    out = "".join(ch for ch in str(cat) if ch.isascii() and ch.isalpha())
    return out.upper() or "GENERAL"


def _assign_symbol_ids(raw_entries, source_code="L"):
    # Give every entry its canonical id: <source><CATEGORY><3-digit seq>.
    # 为每个条目赋予规范 id：<来源码><类别码><三位序号>。
    # Ordering is (category, source_key) so the numbers are stable across re-runs —
    # re-running the generator must never renumber an existing symbol, or every saved
    # *.pid.json would silently point at a different glyph.
    # 排序键为 (类别, 源键)，使序号在重复运行时保持稳定 —— 重跑生成器绝不能给已有图元
    # 重新编号，否则所有已存盘的 *.pid.json 都会静默指向另一个图元。
    seq_by_cat = {}
    for e in sorted(raw_entries, key=lambda x: (x["category"], x["source_key"])):
        cat = e["category"]
        seq_by_cat[cat] = seq_by_cat.get(cat, 0) + 1
        e["seq"] = seq_by_cat[cat]
        e["id"] = "%s%s%03d" % (source_code, _category_code(cat), seq_by_cat[cat])
    return raw_entries


def _write_legacy_map(pack_dir, raw_entries):
    # Persist the old-id -> new-id translation so GPSymbolNaming can keep resolving
    # *.pid.json files written before the naming rule existed.
    # 落盘「旧 id -> 新 id」映射，使 GPSymbolNaming 能继续解析命名规则生效前写下的
    # *.pid.json 文件。
    mapping = {e["source_key"]: e["id"] for e in raw_entries if e["source_key"] != e["id"]}
    path = os.path.join(pack_dir, "legacy_id_map.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(mapping, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")
    print("[legacy] %s: %d aliases -> %s" % (os.path.basename(pack_dir), len(mapping), path))
    return mapping


def _fmt(v):
    v = round(float(v), 4)
    if v == 0:
        return "0"
    if v == int(v):
        return str(int(v))
    return ("%.4f" % v).rstrip("0").rstrip(".")


def _to_gd(v):
    if isinstance(v, dict):
        items = ", ".join('"%s": %s' % (k, _to_gd(val)) for k, val in v.items())
        return "{%s}" % items
    if isinstance(v, (list, tuple)):
        return "[%s]" % ", ".join(_to_gd(x) for x in v)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"%s"' % v.replace("\\", "\\\\").replace('"', '\\"')
    return _fmt(v)


def _process_pack(pack_dir, pack_id, nominal_sizes):
    # Process one pack folder. Returns (pack_meta, entries_list, output_path).
    # 处理一个图元包文件夹，返回 (元数据, 条目列表, 输出路径)。
    manifest_path = os.path.join(pack_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print("[skip] %s: no manifest.json" % pack_id, file=sys.stderr)
        return None, [], None

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    pack_name = manifest.get("name", pack_id)
    standard_ref = manifest.get("standard_ref", "")
    source = manifest.get("source", "")
    license_str = manifest.get("license", "")
    upstream_author = manifest.get("upstream_author", "")

    # ISO 10628 pack: locate mapping.csv for category inference.
    # ISO 10628 包：查找 mapping.csv 用于类别推断。
    csv_path = os.path.join(pack_dir, "mapping.csv")

    # Collect SVG files.
    # 收集 SVG 文件。
    svg_dir = os.path.join(pack_dir, "svg")
    if not os.path.isdir(svg_dir):
        # Try flat layout.
        svg_dir = pack_dir
    svg_files = sorted(f for f in os.listdir(svg_dir) if f.lower().endswith(".svg"))

    if not svg_files:
        print("[warn] %s: no SVG files in %s" % (pack_id, svg_dir), file=sys.stderr)
        return None, [], None

    raw_entries = []
    for fn in svg_files:
        svg_path = os.path.join(svg_dir, fn)
        # Skip legend / non-symbol SVGs.
        # 跳过图例和非图元 SVG。
        base = os.path.splitext(fn)[0]
        if "legend" in base.lower() or "symbols" in base.lower():
            print("[skip] %s: %s (legend/symbol sheet)" % (pack_id, fn), file=sys.stderr)
            continue

        # Determine display name.
        # 确定显示名。
        icon_entry = None
        if manifest.get("icons"):
            for ic in manifest["icons"]:
                if ic.get("file", "").endswith(fn) or ic.get("id") == base:
                    icon_entry = ic
                    break
        display_name = (icon_entry.get("name", base) if icon_entry else base.replace("_", " ").title())
        chinese_name = _chinese_name(pack_id, base)

        # Strip text and extract shapes.
        # 剔除文字并提取形状。
        try:
            root = _strip_text_elements(svg_path)
            result = _shape_with_box(root)
            if result is None:
                print("[skip] %s: %s (no drawable primitives)" % (pack_id, fn), file=sys.stderr)
                continue
            paths, circles, rects, minx, maxx, miny, maxy = result
            shape = _build_shape(paths, circles, rects, minx, maxx, miny, maxy)
        except Exception as e:
            print("[skip] %s: %s (parse error: %s)" % (pack_id, fn, e), file=sys.stderr)
            continue

        # Infer category and ports.
        # 推断类别和端口。
        cat = _infer_category(svg_path, csv_path)
        if icon_entry and icon_entry.get("type"):
            cat = icon_entry["type"]
        env = nominal_sizes.get(cat, (64.0, 64.0))

        raw_entries.append({
            "source_key": base,
            "display_name": display_name,
            "chinese_name": chinese_name,
            "category": cat,
            # Ports are resolved after the canonical ids exist: PORT_OVERRIDES is keyed by
            # canonical id, mirroring GP_PORT_OVERRIDES in symbol_categories.gd.
            # 端口在规范 id 生成后解析：PORT_OVERRIDES 以规范 id 为键，
            # 与 symbol_categories.gd 的 GP_PORT_OVERRIDES 互为镜像。
            "ports": [],
            "shape": shape,
            "env": env,
        })
        print("[ok] %-30s -> %-10s env=%dx%d paths=%d" % (
            base, cat, env[0], env[1], len(paths)))

    # Assign the canonical ids (L<CATEGORY><nnn>) and persist the legacy translation.
    # 分配规范 id（L<类别码><三位序号>）并落盘旧 id 映射。
    entries = _assign_symbol_ids(raw_entries, "L")
    # Now that every entry carries its canonical id, resolve ports against PORT_OVERRIDES.
    # 各条目已持有规范 id，此时再按 PORT_OVERRIDES 解析端口。
    for e in entries:
        e["ports"] = _ports_for(e["id"], e["category"])
        e["tag_prefix"] = _tag_prefix(e["category"])
    _write_legacy_map(pack_dir, entries)
    for e in entries:
        e["ports"] = _ports_for(e["id"], e["category"])
        print("[id] %-32s -> %-14s ports=%d" % (e["source_key"], e["id"], len(e["ports"])))

    # Emit GDScript file.
    # 输出 GDScript 文件。
    out_path = os.path.join(OUT_DIR, "pack_%s.gd" % pack_id)
    # Convert pack_id to a valid Godot class name (e.g., "iso_10628" -> "GPSymbolPackISO10628").
    # 将 pack_id 转换为有效的 Godot 类名（例如 "iso_10628" -> "GPSymbolPackISO10628"）。
    class_name = "GPSymbolPack%s" % "".join(part.capitalize() for part in pack_id.split("-"))
    lines = []
    lines.append(HEADER)
    lines.append("class_name %s" % class_name)
    lines.append("extends RefCounted")
    lines.append("")
    lines.append("")
    lines.append("# Auto-generated symbol definitions for %s." % pack_id)
    lines.append("# 图元包 %s 的自动生成图元定义。")
    if source:
        lines.append("# Source: %s" % source)
    if license_str:
        lines.append("# License: %s" % license_str)
    if upstream_author:
        lines.append("# Upstream author: %s" % upstream_author)
    lines.append("# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。")
    lines.append("")
    lines.append("")
    lines.append("static func gpDefs() -> Array[GPSymbolDef]:")
    lines.append("\tvar gpOut: Array[GPSymbolDef] = []")
    for e in entries:
        env_expr = "Vector2(%s, %s)" % (_fmt(e["env"][0]), _fmt(e["env"][1]))
        lines.append("\tgpOut.append(_gpMk(%s, %s, %s, %s, %s, %s, %s, %s))" % (
            _to_gd(e["id"]), _to_gd(e["chinese_name"]), _to_gd(e["category"]),
            _to_gd(e["ports"]), _to_gd(e["shape"]), env_expr,
            _to_gd(e.get("tag_prefix", "")), _to_gd(_schema_for(e["category"]))))
    lines.append("\treturn gpOut")
    lines.append("")
    lines.append("")
    lines.append("# Internal helper: build one SymbolDef from parsed data.")
    lines.append("# 内部辅助：从解析数据构造一个 SymbolDef。")
    lines.append("static func _gpMk(gpId: String, gpChineseName: String, gpCat: String, "
                "gpPorts: Array[Dictionary], gpShape: Dictionary, gpEnv: Vector2, "
                "gpTagPrefix: String = \"\", "
                "gpSchemaFields: Array[Dictionary] = []) -> GPSymbolDef:")
    lines.append("\tvar gpD: GPSymbolDef = GPSymbolDef.new()")
    lines.append("\tgpD.gpId = gpId")
    lines.append("\tgpD.gpDisplayName = gpChineseName")
    lines.append("\tgpD.gpCategory = gpCat")
    lines.append("\tgpD.gpDefaultSize = gpEnv")
    lines.append("\t# M9: the category's factory tag prefix (\"P\" for a pump). The runtime")
    lines.append("\t# falls back to the category table when this is empty.")
    lines.append("\t# M9：类别的出厂位号前缀（泵为 \"P\"）。为空时运行期回落到类别表。")
    lines.append("\tgpD.gpTagPrefix = gpTagPrefix")
    lines.append("\t# P0 unified model: the generated dict specs are converted into the shared "
                 "GPShape / GPPort")
    lines.append("\t# types here, so the library, the editor and the canvas all consume one model.")
    lines.append("\t# P0 统一模型：此处把生成的字典规格转换为共用的 GPShape / GPPort 类型，")
    lines.append("\t# 使图元库、编辑器与画布共用同一模型。")
    lines.append("\tgpD.gpPorts = GPPortSpec.gpFromDicts(gpPorts)")
    lines.append("\tgpD.gpShapes = GPShapeSpec.gpFromSpec(gpShape)")
    lines.append("\t# M8: wire the typed property schema. It was BUILT but never ASSIGNED, so the")
    lines.append("\t# inspector had no fields to show for factory symbols — this is the missing")
    lines.append("\t# half of \"edit the library, every project follows\".")
    lines.append("\t# M8：接上类型化属性 schema。它此前「已建成但未赋值」，导致出厂图元在属性面板里")
    lines.append("\t# 无字段可显示 —— 这正是「改库即全项目同步」缺失的那一半。")
    lines.append("\tif not gpSchemaFields.is_empty():")
    lines.append("\t\tvar gpSc: GPPropertySchema = GPPropertySchema.new()")
    lines.append("\t\tfor gpF in gpSchemaFields:")
    lines.append("\t\t\tvar gpPd: GPPropertyDef = GPPropertyDef.new()")
    lines.append("\t\t\tgpPd.gpFromDict(gpF as Dictionary)")
    lines.append("\t\t\tgpSc.gpFields.append(gpPd)")
    lines.append("\t\tgpD.gpSchema = gpSc")
    lines.append("\treturn gpD")
    lines.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    pack_meta = {
        "pack_id": pack_id,
        "name": pack_name,
        "standard_ref": standard_ref,
        "license": license_str,
        "author": upstream_author,
        "entry_count": len(entries),
        "out_path": out_path,
    }
    return pack_meta, entries, out_path


# ---------------------------------------------------------------------------
# Typed property schemas per category (M8 "通电" / wiring the built schema up).
# 按类别的类型化属性 schema（M8：把已建成的 schema 通上电）。
#
# WHY HERE / 为何放在生成器：field DEFINITIONS belong to the TYPE layer, and the factory
# pack is generated — so the schema is emitted into pack_*.gd instead of being hand-written
# per symbol. Editing one category here propagates to every symbol of that category.
# 字段**定义**属类型层，而出厂图元包是生成的 —— 故 schema 由生成器写入 pack_*.gd，
# 而非逐图元手写。此处改一个类别，该类别所有图元随之生效。
#
# kind ints mirror GPPropertyDef.GPKind:
#   0 STRING / 1 INT / 2 FLOAT / 3 BOOL / 4 ENUM / 5 TEXT / 6 MULTILANG
#
# label_key is deliberately left EMPTY: gpLabel carries the Chinese fallback, so we do not
# have to touch the i18n tables and gp_test_i18n_keys stays green. Adding i18n keys later is
# a pure additive change (set label_key, add the key to the i18n source).
# label_key 故意留空：由 gpLabel 提供中文回落，故无需改动 i18n 表，gp_test_i18n_keys 保持绿。
# 后续补 i18n 是纯增量改动（填 label_key + 在 i18n 源加键）。
CATEGORY_SCHEMA = {
    "pump": [
        {"key": "rated_flow", "label": "额定流量", "kind": 2, "unit": "m3/h",
         "group": "工艺", "order": 10},
        {"key": "rated_head", "label": "额定扬程", "kind": 2, "unit": "m",
         "group": "工艺", "order": 20},
        {"key": "motor_power", "label": "电机功率", "kind": 2, "unit": "kW",
         "group": "电气", "order": 30},
        {"key": "seal_type", "label": "密封型式", "kind": 4,
         "group": "机械", "order": 40,
         "options": ["机械密封", "填料密封", "磁力驱动"]},
        {"key": "material", "label": "过流部件材质", "kind": 4,
         "group": "材料", "order": 50,
         "options": ["铸铁", "碳钢", "304不锈钢", "316L不锈钢", "双相钢"]},
        {"key": "remark", "label": "备注", "kind": 5, "group": "工艺", "order": 90},
    ],
    "valve": [
        {"key": "nominal_size", "label": "公称通径", "kind": 2, "unit": "mm",
         "group": "工艺", "order": 10},
        {"key": "pressure_rating", "label": "压力等级", "kind": 4,
         "group": "工艺", "order": 20,
         "options": ["PN10", "PN16", "PN25", "PN40", "Class150", "Class300"]},
        {"key": "body_material", "label": "阀体材质", "kind": 4,
         "group": "材料", "order": 30,
         "options": ["铸铁", "碳钢", "304不锈钢", "316L不锈钢", "衬氟"]},
        {"key": "actuator_type", "label": "执行机构", "kind": 4,
         "group": "仪表", "order": 40,
         "options": ["手动", "气动", "电动", "液动", "无"]},
        {"key": "fail_action", "label": "故障安全位", "kind": 4,
         "group": "仪表", "order": 50,
         "options": ["FC 故障关", "FO 故障开", "FL 故障保位", "不适用"]},
        {"key": "remark", "label": "备注", "kind": 5, "group": "工艺", "order": 90},
    ],
    "tank": [
        {"key": "volume", "label": "容积", "kind": 2, "unit": "m3",
         "group": "工艺", "order": 10},
        {"key": "design_pressure", "label": "设计压力", "kind": 2, "unit": "MPa",
         "group": "工艺", "order": 20},
        {"key": "design_temp", "label": "设计温度", "kind": 2, "unit": "℃",
         "group": "工艺", "order": 30},
        {"key": "material", "label": "材质", "kind": 4, "group": "材料", "order": 40,
         "options": ["碳钢", "304不锈钢", "316L不锈钢", "衬胶", "FRP"]},
        {"key": "remark", "label": "备注", "kind": 5, "group": "工艺", "order": 90},
    ],
    "heat": [
        {"key": "heat_area", "label": "换热面积", "kind": 2, "unit": "m2",
         "group": "工艺", "order": 10},
        {"key": "duty", "label": "热负荷", "kind": 2, "unit": "kW",
         "group": "工艺", "order": 20},
        {"key": "design_pressure", "label": "设计压力", "kind": 2, "unit": "MPa",
         "group": "工艺", "order": 30},
        {"key": "design_temp", "label": "设计温度", "kind": 2, "unit": "℃",
         "group": "工艺", "order": 40},
        {"key": "material", "label": "材质", "kind": 4, "group": "材料", "order": 50,
         "options": ["碳钢", "304不锈钢", "316L不锈钢", "钛"]},
        {"key": "remark", "label": "备注", "kind": 5, "group": "工艺", "order": 90},
    ],
    "instrument": [
        {"key": "measure_range", "label": "量程", "kind": 0,
         "group": "仪表", "order": 10},
        {"key": "signal_type", "label": "信号类型", "kind": 4,
         "group": "仪表", "order": 20,
         "options": ["4-20mA", "4-20mA+HART", "Profibus PA",
                     "Foundation Fieldbus", "开关量"]},
        {"key": "accuracy", "label": "精度", "kind": 0, "group": "仪表", "order": 30},
        {"key": "power_supply", "label": "供电", "kind": 4, "group": "电气", "order": 40,
         "options": ["24VDC", "220VAC", "无源"]},
        {"key": "remark", "label": "备注", "kind": 5, "group": "仪表", "order": 90},
    ],
    "general": [
        {"key": "description", "label": "描述", "kind": 5, "group": "工艺", "order": 10},
    ],
}


def _schema_for(cat):
    # Per-category typed schema; unknown categories get none (gpSchema stays null and the
    # runtime falls back to gpAttrsSchema).
    # 按类别取类型化 schema；未知类别返回空（gpSchema 保持 null，运行期回落 gpAttrsSchema）。
    return CATEGORY_SCHEMA.get(cat, [])


def _chinese_name(pack_id, base_id):
    # Return Chinese display name from known mappings; fall back to base_id.
    # 返回已知映射的中文显示名；找不到时回退为 base_id。
    iso_chinese = {
        "FT_FlowTransmitter_001": "流量变送器",
        "PT_PressureTransmitter_001": "压力变送器",
        "TT_TemperatureTransmitter_001": "温度变送器",
        "LT_LevelTransmitter_001": "液位变送器",
        "FI_FlowIndicator_001": "流量指示器",
        "PI_PressureIndicator_001": "压力指示器",
        "TI_TemperatureIndicator_001": "温度指示器",
        "LI_LevelIndicator_001": "液位指示器",
        "CV_ControlValve_001": "调节阀",
        "BV_BallValve_001": "球阀",
        "GV_GateValve_001": "闸阀",
        "GLV_GlobeValve_001": "截止阀",
        "CHK_CheckValve_001": "止回阀",
        "DV_DiaphragmValve_001": "隔膜阀",
        "VAV_ValveActuator_001": "阀门执行器",
        "PV_Positioner_001": "阀门定位器",
        "P_CentrifugalPump_001": "离心泵",
        "PD_PositiveDisplacementPump_001": "容积泵",
        "C_Compressor_001": "压缩机",
        "HX_HeatExchanger_001": "换热器",
        "TK_Tank_001": "储罐",
        "FE_FieldEnclosure_001": "现场接线箱",
    }
    iec_chinese = {
        "hand_operated_gate_valve": "手动闸阀",
        "gate_valve": "闸阀",
        "hand_operated_globe_valve": "手动截止阀",
        "rotary_valve": "旋转阀",
        "check_valve": "止回阀",
        "tank": "储罐",
    }
    lookup = iso_chinese if pack_id == "iso_10628" else iec_chinese
    return lookup.get(base_id, base_id.replace("_", " ").title())


def _run():
    nominal_sizes = _read_nominal()
    print("Nominal sizes: %s" % nominal_sizes)

    if not os.path.isdir(PACKS_DIR):
        print("[error] %s not found" % PACKS_DIR, file=sys.stderr)
        sys.exit(1)

    pack_ids = sorted(d for d in os.listdir(PACKS_DIR)
                      if os.path.isdir(os.path.join(PACKS_DIR, d)))
    print("Discovered packs: %s" % pack_ids)

    all_meta = []
    all_entries_by_pack = {}
    for pack_id in pack_ids:
        pack_dir = os.path.join(PACKS_DIR, pack_id)
        meta, entries, out_path = _process_pack(pack_dir, pack_id, nominal_sizes)
        if meta:
            all_meta.append(meta)
            all_entries_by_pack[pack_id] = entries
            print("-> %s (%d defs)" % (out_path, len(entries)))

    # Write pack registry summary (for reference / 供参考)。
    reg_path = os.path.join(OUT_DIR, "_pack_registry.json")
    with open(reg_path, "w", encoding="utf-8") as f:
        json.dump(all_meta, f, ensure_ascii=False, indent=2)
    print("\nWrote pack registry to %s" % reg_path)
    print("Total packs: %d" % len(all_meta))


if __name__ == "__main__":
    _run()
