#!/usr/bin/env python3
# tools/gen_symbol_packs.py
# Unified symbol pack generator.
# 统一图元包生成器。
#
# Reads every subfolder of assets/symbol_packs/ that contains a manifest.json,
# strips text from each SVG, normalizes shape primitives into the 100x100 unit
# box, emits a GDScript defs file under src/core/symbol_packs/.
# 读取 assets/symbol_packs/ 下每个含 manifest.json 的子包，
# 剔除 SVG 中的 text 元素，把形状原语归一化到 100x100 单位框，
# 并在 src/core/symbol_packs/ 下生成对应的 GDScript 定义文件。
#
# Usage / 用法:
#   python3 tools/gen_symbol_packs.py
#
# Output / 输出:
#   src/core/symbol_packs/pack_<pack_id>.gd   (one per discovered pack)
#                                              （每个已发现的图元包输出一个文件）

import json
import os
import re
import sys
import xml.etree.ElementTree as ET

# Reuse the path parser from the sibling converter.
# 复用同目录转换器的路径解析器。
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import svg_to_gpsym as S  # noqa: E402
from svg_to_gpsym import _apply, _mul, _parse_transform  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Godot-PID-Core
PACKS_DIR = os.path.join(ROOT, "assets", "symbol_packs")
OUT_DIR = os.path.join(ROOT, "src", "core", "symbol_packs")

# License header for every emitted GDScript file.
# 每个输出 GDScript 文件的许可证头。
HEADER = """\
# Copyright © 2026 Jonson Wang
# Auto-generated by tools/gen_symbol_packs.py — DO NOT edit by hand.
# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。
"""


def _read_nominal():
    # Parse GP_NOMINAL from src/core/symbol_categories.gd so sizes stay in sync.
    # 从 src/core/symbol_categories.gd 解析 GP_NOMINAL，使尺寸与枚举表保持一致。
    cat_path = os.path.join(ROOT, "src", "core", "symbol_categories.gd")
    with open(cat_path, "r", encoding="utf-8") as f:
        text = f.read()
    block = re.search(r"const\s+GP_NOMINAL[^{]*\{(.*?)\}", text, re.S)
    sizes = {}
    if block:
        for k, w, h in re.findall(
            r'"([^"]+)"\s*:\s*Vector2\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)', block.group(1)
        ):
            sizes[k] = (float(w), float(h))
    return sizes


def _strip_text_elements(svg_path):
    # Parse SVG, remove all <text> elements, return new XML root.
    # 解析 SVG，删除所有 <text> 元素，返回新根节点。
    tree = ET.parse(svg_path)
    ns = "http://www.w3.org/2000/svg"
    for t in list(tree.getroot().iter(ns + "text")):
        t.getparent().remove(t)
    return tree.getroot()


def _shape_with_box(root, size=100):
    # Use svg_to_gpsym._collect for full SVG element support, then compute unit-box.
    # 用 svg_to_gpsym._collect 处理完整 SVG 元素，再计算单位空间包围盒。
    # Returns (paths, circles, rects, minx, maxx, miny, maxy) in the ORIGINAL SVG coords.
    # 返回原始 SVG 坐标系下的 (折线列表, 圆列表, 矩形列表, 包围盒).
    result = S._collect(root, size, "general")
    if result is None:
        return None
    # _collect already normalizes into 100x100; we need the ORIGINAL bounding box
    # to compute the "box" field. Walk the original root for raw pts.
    ns = "http://www.w3.org/2000/svg"
    raw_pts = []
    def walk(el, m):
        if "transform" in el.attrib:
            m = S._mul(m, S._parse_transform(el.attrib["transform"]))
        tag = S._localname(el.tag)
        if tag in ("path", "rect", "circle", "line", "polygon", "polyline"):
            if tag == "line":
                x1 = float(el.attrib.get("x1", 0)); y1 = float(el.attrib.get("y1", 0))
                x2 = float(el.attrib.get("x2", 0)); y2 = float(el.attrib.get("y2", 0))
                raw_pts.append(S._apply(m, x1, y1)); raw_pts.append(S._apply(m, x2, y2))
            elif tag == "rect":
                x = float(el.attrib.get("x", 0)); y = float(el.attrib.get("y", 0))
                w = float(el.attrib.get("width", 0)); h = float(el.attrib.get("height", 0))
                for px, py in [(x, y), (x+w, y), (x, y+h), (x+w, y+h)]:
                    raw_pts.append(S._apply(m, px, py))
            elif tag == "circle":
                cx = float(el.attrib.get("cx", 0)); cy = float(el.attrib.get("cy", 0))
                r = float(el.attrib.get("r", 0))
                raw_pts.append(S._apply(m, cx-r, cy-r)); raw_pts.append(S._apply(m, cx+r, cy+r))
            elif tag == "path":
                d = el.attrib.get("d", "")
                for poly, _ in S._path_to_polylines(d):
                    for p in poly:
                        raw_pts.append(S._apply(m, p[0], p[1]))
        for child in el:
            walk(child, m)
    walk(root, S._ident())
    if not raw_pts:
        return None
    xs = [p[0] for p in raw_pts]; ys = [p[1] for p in raw_pts]
    minx, maxx = min(xs), max(xs); miny, maxy = min(ys), max(ys)
    return result["paths"], result["circles"], result["rects"], minx, maxx, miny, maxy


def _build_shape(paths, circles, rects, minx, maxx, miny, maxy):
    # Build gpShape dict with box field (unit-space bbox).
    # 构建 gpShape 字典，含单位空间包围盒 box。
    uw = (maxx - minx) or 1.0
    uh = (maxy - miny) or 1.0
    box = [round(50.0 - uw * 0.5, 2), round(50.0 - uh * 0.5, 2), round(uw, 2), round(uh, 2)]
    return {"paths": paths, "circles": circles, "rects": rects, "box": box}


def _infer_category(svg_path, csv_path):
    # Infer category from SVG filename using mapping.csv (ISO) or icon "type" field (IEC).
    # 通过 mapping.csv（ISO）或图标 "type" 字段（IEC）从文件名推断类别。
    base = os.path.splitext(os.path.basename(svg_path))[0]
    cat = "general"
    if csv_path and os.path.exists(csv_path):
        with open(csv_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith(base + ",") or f'"{base}.svg"' in line:
                    parts = line.strip().split(",")
                    if len(parts) >= 2:
                        isa_code = parts[1].strip()
                        # Map ISA code to category.
                        # 把 ISA 代码映射到类别。
                        cat_map = {
                            "P": "pump", "PD": "pump", "C": "pump",
                            "GV": "valve", "GLV": "valve", "BV": "valve",
                            "CHK": "valve", "DV": "valve", "CV": "valve",
                            "VAV": "valve", "PV": "valve",
                            "TK": "tank",
                            "HX": "heat",
                            "FT": "instrument", "PT": "instrument", "TT": "instrument",
                            "LT": "instrument", "FI": "instrument", "PI": "instrument",
                            "TI": "instrument", "LI": "instrument", "FE": "instrument",
                            "LINE-P": "pipe", "LINE-I": "pipe", "LINE-E": "pipe",
                        }
                        cat = cat_map.get(isa_code, "general")
                        break
    return cat


def _infer_ports_svg(svg_path, cat):
    # Infer port positions from SVG geometry (left/right for valve/pump, top/bottom for tank).
    # 根据 SVG 几何推断端口位置（阀门/泵取左右，储罐取上下）。
    ns = "http://www.w3.org/2000/svg"
    tree = ET.parse(svg_path)
    root = tree.getroot()
    pts = []
    for el in root.iter():
        if el.tag == ns + "line":
            x1 = float(el.attrib.get("x1", 0)); y1 = float(el.attrib.get("y1", 0))
            x2 = float(el.attrib.get("x2", 0)); y2 = float(el.attrib.get("y2", 0))
            pts.append((x1, y1)); pts.append((x2, y2))
        elif el.tag == ns + "rect":
            x = float(el.attrib.get("x", 0)); y = float(el.attrib.get("y", 0))
            w = float(el.attrib.get("width", 0)); h = float(el.attrib.get("height", 0))
            pts.append((x, y)); pts.append((x + w, y + h))
    if not pts:
        return []
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    minx, maxx = min(xs), max(xs); miny, maxy = min(ys), max(ys)
    bw = maxx - minx or 1; bh = maxy - miny or 1
    cx = (minx + maxx) / 2; cy = (miny + maxy) / 2

    if cat == "valve":
        # Left and right midpoints.
        # 左中点和右中点。
        return [
            {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0]},
            {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0]},
        ]
    elif cat == "pump":
        return [
            {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0]},
            {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0]},
        ]
    elif cat == "tank":
        return [
            {"name": "top", "pos": [0.5, 0.0], "dir": [0, -1]},
            {"name": "bottom", "pos": [0.5, 1.0], "dir": [0, 1]},
        ]
    elif cat == "instrument":
        return [
            {"name": "in", "pos": [0.5, 1.0], "dir": [0, 1]},
        ]
    elif cat in ("heat",):
        return [
            {"name": "in", "pos": [0.0, 0.5], "dir": [-1, 0]},
            {"name": "out", "pos": [1.0, 0.5], "dir": [1, 0]},
        ]
    return []


def _fmt(v):
    v = round(float(v), 4)
    if v == 0:
        return "0"
    if v == int(v):
        return str(int(v))
    return ("%.4f" % v).rstrip("0").rstrip(".")


def _to_gd(v):
    if isinstance(v, dict):
        items = ", ".join('"%s": %s' % (k, _to_gd(val)) for k, val in v.items())
        return "{%s}" % items
    if isinstance(v, (list, tuple)):
        return "[%s]" % ", ".join(_to_gd(x) for x in v)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"%s"' % v.replace("\\", "\\\\").replace('"', '\\"')
    return _fmt(v)


def _process_pack(pack_dir, pack_id, nominal_sizes):
    # Process one pack folder. Returns (pack_meta, entries_list, output_path).
    # 处理一个图元包文件夹，返回 (元数据, 条目列表, 输出路径)。
    manifest_path = os.path.join(pack_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        print("[skip] %s: no manifest.json" % pack_id, file=sys.stderr)
        return None, [], None

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    pack_name = manifest.get("name", pack_id)
    standard_ref = manifest.get("standard_ref", "")
    source = manifest.get("source", "")
    license_str = manifest.get("license", "")
    upstream_author = manifest.get("upstream_author", "")

    # ISO 10628 pack: locate mapping.csv for category inference.
    # ISO 10628 包：查找 mapping.csv 用于类别推断。
    csv_path = os.path.join(pack_dir, "mapping.csv")

    # Collect SVG files.
    # 收集 SVG 文件。
    svg_dir = os.path.join(pack_dir, "svg")
    if not os.path.isdir(svg_dir):
        # Try flat layout.
        svg_dir = pack_dir
    svg_files = sorted(f for f in os.listdir(svg_dir) if f.lower().endswith(".svg"))

    if not svg_files:
        print("[warn] %s: no SVG files in %s" % (pack_id, svg_dir), file=sys.stderr)
        return None, [], None

    entries = []
    for fn in svg_files:
        svg_path = os.path.join(svg_dir, fn)
        # Skip legend / non-symbol SVGs.
        # 跳过图例和非图元 SVG。
        base = os.path.splitext(fn)[0]
        if "legend" in base.lower() or "symbols" in base.lower():
            print("[skip] %s: %s (legend/symbol sheet)" % (pack_id, fn), file=sys.stderr)
            continue

        # Determine display name.
        # 确定显示名。
        icon_entry = None
        if manifest.get("icons"):
            for ic in manifest["icons"]:
                if ic.get("file", "").endswith(fn) or ic.get("id") == base:
                    icon_entry = ic
                    break
        display_name = (icon_entry.get("name", base) if icon_entry else base.replace("_", " ").title())
        chinese_name = _chinese_name(pack_id, base)

        # Strip text and extract shapes.
        # 剔除文字并提取形状。
        try:
            root = _strip_text_elements(svg_path)
            result = _shape_with_box(root)
            if result is None:
                print("[skip] %s: %s (no drawable primitives)" % (pack_id, fn), file=sys.stderr)
                continue
            paths, circles, rects, minx, maxx, miny, maxy = result
            shape = _build_shape(paths, circles, rects, minx, maxx, miny, maxy)
        except Exception as e:
            print("[skip] %s: %s (parse error: %s)" % (pack_id, fn, e), file=sys.stderr)
            continue

        # Infer category and ports.
        # 推断类别和端口。
        cat = _infer_category(svg_path, csv_path)
        if icon_entry and icon_entry.get("type"):
            cat = icon_entry["type"]
        ports = _infer_ports_svg(svg_path, cat)
        env = nominal_sizes.get(cat, (64.0, 64.0))

        entries.append({
            "id": base,
            "display_name": display_name,
            "chinese_name": chinese_name,
            "category": cat,
            "ports": ports,
            "shape": shape,
            "env": env,
        })
        print("[ok] %-30s -> %-10s env=%dx%d paths=%d ports=%d" % (
            base, cat, env[0], env[1], len(paths), len(ports)))

    # Emit GDScript file.
    # 输出 GDScript 文件。
    out_path = os.path.join(OUT_DIR, "pack_%s.gd" % pack_id)
    # Convert pack_id to a valid Godot class name (e.g., "iso_10628" -> "GPSymbolPackISO10628").
    # 将 pack_id 转换为有效的 Godot 类名（例如 "iso_10628" -> "GPSymbolPackISO10628"）。
    class_name = "GPSymbolPack%s" % "".join(part.capitalize() for part in pack_id.split("-"))
    lines = []
    lines.append(HEADER)
    lines.append("class_name %s" % class_name)
    lines.append("extends RefCounted")
    lines.append("")
    lines.append("")
    lines.append("# Auto-generated symbol definitions for %s." % pack_id)
    lines.append("# 图元包 %s 的自动生成图元定义。")
    if source:
        lines.append("# Source: %s" % source)
    if license_str:
        lines.append("# License: %s" % license_str)
    if upstream_author:
        lines.append("# Upstream author: %s" % upstream_author)
    lines.append("# 自动生成，请勿手改；修改请编辑 tools/gen_symbol_packs.py 后重跑。")
    lines.append("")
    lines.append("")
    lines.append("static func gpDefs() -> Array[GPSymbolDef]:")
    lines.append("\tvar gpOut: Array[GPSymbolDef] = []")
    for e in entries:
        env_expr = "Vector2(%s, %s)" % (_fmt(e["env"][0]), _fmt(e["env"][1]))
        lines.append("\tgpOut.append(_gpMk(%s, %s, %s, %s, %s, %s))" % (
            _to_gd(e["id"]), _to_gd(e["chinese_name"]), _to_gd(e["category"]),
            _to_gd(e["ports"]), _to_gd(e["shape"]), env_expr))
    lines.append("\treturn gpOut")
    lines.append("")
    lines.append("")
    lines.append("# Internal helper: build one SymbolDef from parsed data.")
    lines.append("# 内部辅助：从解析数据构造一个 SymbolDef。")
    lines.append("static func _gpMk(gpId: String, gpChineseName: String, gpCat: String, "
                "gpPorts: Array[Dictionary], gpShape: Dictionary, gpEnv: Vector2) -> GPSymbolDef:")
    lines.append("\tvar gpD: GPSymbolDef = GPSymbolDef.new()")
    lines.append("\tgpD.gpId = gpId")
    lines.append("\tgpD.gpDisplayName = gpChineseName")
    lines.append("\tgpD.gpCategory = gpCat")
    lines.append("\tgpD.gpDefaultSize = gpEnv")
    lines.append("\tgpD.gpPorts = gpPorts")
    lines.append("\tgpD.gpShape = gpShape")
    lines.append("\treturn gpD")
    lines.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    pack_meta = {
        "pack_id": pack_id,
        "name": pack_name,
        "standard_ref": standard_ref,
        "license": license_str,
        "author": upstream_author,
        "entry_count": len(entries),
        "out_path": out_path,
    }
    return pack_meta, entries, out_path


def _chinese_name(pack_id, base_id):
    # Return Chinese display name from known mappings; fall back to base_id.
    # 返回已知映射的中文显示名；找不到时回退为 base_id。
    iso_chinese = {
        "FT_FlowTransmitter_001": "流量变送器",
        "PT_PressureTransmitter_001": "压力变送器",
        "TT_TemperatureTransmitter_001": "温度变送器",
        "LT_LevelTransmitter_001": "液位变送器",
        "FI_FlowIndicator_001": "流量指示器",
        "PI_PressureIndicator_001": "压力指示器",
        "TI_TemperatureIndicator_001": "温度指示器",
        "LI_LevelIndicator_001": "液位指示器",
        "CV_ControlValve_001": "调节阀",
        "BV_BallValve_001": "球阀",
        "GV_GateValve_001": "闸阀",
        "GLV_GlobeValve_001": "截止阀",
        "CHK_CheckValve_001": "止回阀",
        "DV_DiaphragmValve_001": "隔膜阀",
        "VAV_ValveActuator_001": "阀门执行器",
        "PV_Positioner_001": "阀门定位器",
        "P_CentrifugalPump_001": "离心泵",
        "PD_PositiveDisplacementPump_001": "容积泵",
        "C_Compressor_001": "压缩机",
        "HX_HeatExchanger_001": "换热器",
        "TK_Tank_001": "储罐",
        "FE_FieldEnclosure_001": "现场接线箱",
    }
    iec_chinese = {
        "hand_operated_gate_valve": "手动闸阀",
        "gate_valve": "闸阀",
        "hand_operated_globe_valve": "手动截止阀",
        "rotary_valve": "旋转阀",
        "check_valve": "止回阀",
        "tank": "储罐",
    }
    lookup = iso_chinese if pack_id == "iso_10628" else iec_chinese
    return lookup.get(base_id, base_id.replace("_", " ").title())


def _run():
    nominal_sizes = _read_nominal()
    print("Nominal sizes: %s" % nominal_sizes)

    if not os.path.isdir(PACKS_DIR):
        print("[error] %s not found" % PACKS_DIR, file=sys.stderr)
        sys.exit(1)

    pack_ids = sorted(d for d in os.listdir(PACKS_DIR)
                      if os.path.isdir(os.path.join(PACKS_DIR, d)))
    print("Discovered packs: %s" % pack_ids)

    all_meta = []
    all_entries_by_pack = {}
    for pack_id in pack_ids:
        pack_dir = os.path.join(PACKS_DIR, pack_id)
        meta, entries, out_path = _process_pack(pack_dir, pack_id, nominal_sizes)
        if meta:
            all_meta.append(meta)
            all_entries_by_pack[pack_id] = entries
            print("-> %s (%d defs)" % (out_path, len(entries)))

    # Write pack registry summary (for reference / 供参考)。
    reg_path = os.path.join(OUT_DIR, "_pack_registry.json")
    with open(reg_path, "w", encoding="utf-8") as f:
        json.dump(all_meta, f, ensure_ascii=False, indent=2)
    print("\nWrote pack registry to %s" % reg_path)
    print("Total packs: %d" % len(all_meta))


if __name__ == "__main__":
    _run()
